### ISSUE TITLE
As a student working on this project I want to have clean annotated databases so that prof. Dhrumil sees we followed instructions

### ISSUE THREAD

**Issue by nomkob** [code4policy/covid-aid-impact#26]
- a copy of the original data in the format you got it in
- a README.md or README.txt file with a link to the original data source and an explanation about how you transformed the original data into the final format you needed. If you've done the transformation using a python script (or in any other programming language), just uplaod that script -- no need to document. Just comments within the code will be sufficient. If you used some other means, please document your data transformation process in the README file. It should be a step by step explanation, not just one pithy sentence like "I transformed the data with excel".
- a copy of the final data which will be consumed by the visualization

**Comment by pranavbhargava89** [comment]
Uploaded the final updated data files, code files and Readme files to explain the data cleaning process
