### ISSUE TITLE
As an academic researcher, I want to see the change in international aid to developing countries sectors over time so that it aids in my research and class presentations

### ISSUE THREAD

**Issue by nomkob** [code4policy/covid-aid-impact#30]

**Comment by nomkob** [comment]
## Invest
- [x] Independent
- [x] Negotiable
- [x] Valuable
- [x] Estimable
- [x] Small
- [x] Testable

## Tasks
Investigate sectoral data more thoroughly and identify trends ()
Play around with visualization options

## Definition of done
Show sectoral COVID aid trends on the website

**Comment by pranavbhargava89** [comment]
Sectoral COVID trends can be seen on the viz on the website
