### ISSUE TITLE
As a student exploring the data presented on Tableau, I want to see updated visualizations/features so that the dashboards are more intuitive

### ISSUE THREAD

**Issue by nomkob** [code4policy/covid-aid-impact#44]
## Tasks:
Overall:
- Remove arrows on top if there are only 3 tabs (that fit on the page anyway)

1st tab
- Remove focus from ADB and USDA to cover more general donor aid trends (hover chart should accurately add up to 100 based on all aid from all organizations in list) 
- add filter that enables choosing the donor organization
- remove null and 2050 for year values

2nd tab
- replace bar charts by a single horizontal line graph showing just the trend in yoy changes, the exact amount could be in tooltip 
- add filter for donor organization that toggles the graph
- rename 'Year of Year' to just 'Year'
- space out text so that there are no ellipses 

3rd tab:
- replace bar charts by a single horizontal line graph showing just the trend in yoy changes, the exact amount could be in tooltip 
- rename 'Year of Year' to just 'Year'
- add filter for donor organization 
- add ability to choose several countries
- add filter for regions 
- add filter for sectors
- remove null from country values

**Comment by pranavbhargava89** [comment]
Updated the visualisations with the above comments. Reflected changes can be seen on the viz on the website
